### ISSUE TITLE
Viewing user profile gives an error

### ISSUE THREAD

**Issue by NonlinearFruit** [caelum/mamute#261]
User Profile Error
----------------------
When I log onto my mamute instance and click my profile, I receive a `org.hibernate.exception.SQLGrammarException: could not extract ResultSet` error. It looks like this:

![screenshot from 2016-06-29 16-41-39](https://cloud.githubusercontent.com/assets/6962125/16468293/2bddbd04-3e19-11e6-955c-168ce01d91b8.png)

The error also shows up when I am browsing anonymously and click on someone's profile.

**Comment by felipeweb** [comment]
@NonlinearFruit  Do want to send PR to fix that?

**Comment by felipeweb** [comment]
the bug is fixed. @NonlinearFruit  could you  pull the repository and test?

**Comment by code4passion** [comment]
@felipeweb Pulled the latest code ,Still getting same issue. LAstest commit i have is commit 9b22c3343733db2afe0914453c24db0fcaad221f

  Merge pull request #264 from jasonwjones/master
    
    SSL, news hiding, and login redirect fixes

**Comment by felipeweb** [comment]
@code4passion thank you for your feedback, i will try reproduce the bug on my machine and fix it asap

**Comment by code4passion** [comment]
@felipeweb Sent a pullrequest for this error. I did ran unit test to verify that nothing is breaking.Do i need to run any other tests? Was not sure how do i run integ tests.Let me know.
